// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GibbsSamplerCpp
Rcpp::List GibbsSamplerCpp(arma::mat M, arma::mat W, arma::cube Z, arma::mat P, arma::mat E, arma::mat Ap, arma::mat Bp, arma::mat Ae, arma::mat Be, double ap, double bp, double ae, double be, double lp, double le, double var_ap, double var_ae, int burn, int eval, bool Pfixed, bool Zfixed, bool Thetafixed, bool Afixed, bool keep_par);
RcppExport SEXP _signeR_GibbsSamplerCpp(SEXP MSEXP, SEXP WSEXP, SEXP ZSEXP, SEXP PSEXP, SEXP ESEXP, SEXP ApSEXP, SEXP BpSEXP, SEXP AeSEXP, SEXP BeSEXP, SEXP apSEXP, SEXP bpSEXP, SEXP aeSEXP, SEXP beSEXP, SEXP lpSEXP, SEXP leSEXP, SEXP var_apSEXP, SEXP var_aeSEXP, SEXP burnSEXP, SEXP evalSEXP, SEXP PfixedSEXP, SEXP ZfixedSEXP, SEXP ThetafixedSEXP, SEXP AfixedSEXP, SEXP keep_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type E(ESEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bp(BpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ae(AeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Be(BeSEXP);
    Rcpp::traits::input_parameter< double >::type ap(apSEXP);
    Rcpp::traits::input_parameter< double >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< double >::type ae(aeSEXP);
    Rcpp::traits::input_parameter< double >::type be(beSEXP);
    Rcpp::traits::input_parameter< double >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< double >::type le(leSEXP);
    Rcpp::traits::input_parameter< double >::type var_ap(var_apSEXP);
    Rcpp::traits::input_parameter< double >::type var_ae(var_aeSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type eval(evalSEXP);
    Rcpp::traits::input_parameter< bool >::type Pfixed(PfixedSEXP);
    Rcpp::traits::input_parameter< bool >::type Zfixed(ZfixedSEXP);
    Rcpp::traits::input_parameter< bool >::type Thetafixed(ThetafixedSEXP);
    Rcpp::traits::input_parameter< bool >::type Afixed(AfixedSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_par(keep_parSEXP);
    rcpp_result_gen = Rcpp::wrap(GibbsSamplerCpp(M, W, Z, P, E, Ap, Bp, Ae, Be, ap, bp, ae, be, lp, le, var_ap, var_ae, burn, eval, Pfixed, Zfixed, Thetafixed, Afixed, keep_par));
    return rcpp_result_gen;
END_RCPP
}
