// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP signeR_GibbsSamplerCpp(SEXP MSEXP, SEXP WSEXP, SEXP ZSEXP, SEXP PSEXP,
    SEXP ESEXP, SEXP ApSEXP, SEXP BpSEXP, SEXP AeSEXP, SEXP BeSEXP, SEXP apSEXP,
    SEXP bpSEXP, SEXP aeSEXP, SEXP beSEXP, SEXP lpSEXP, SEXP leSEXP,
    SEXP var_apSEXP, SEXP var_aeSEXP, SEXP burnSEXP, SEXP evalSEXP,
    SEXP ZfixedSEXP, SEXP ThetafixedSEXP, SEXP AfixedSEXP, SEXP keep_parSEXP);

R_CallMethodDef callMethods[]  = {
    {"signeR_GibbsSamplerCpp", (DL_FUNC) &signeR_GibbsSamplerCpp, 23},
    {NULL, NULL, 0}
};

void R_init_signeR(DllInfo *info) {
    R_registerRoutines(info, NULL, callMethods, NULL, NULL);
    R_useDynamicSymbols(info, FALSE);
}

