# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FuzzyClusterCpp <- function(Exp, Medx, C, m, thresh) {
    .Call(`_signeR_FuzzyClusterCpp`, Exp, Medx, C, m, thresh)
}

GibbsSamplerCpp <- function(M, W, Z, P, E, Ap, Bp, Ae, Be, ap, bp, ae, be, lp, le, var_ap, var_ae, burn, eval, Pfixed, Zfixed, Thetafixed, Afixed, keep_par) {
    .Call(`_signeR_GibbsSamplerCpp`, M, W, Z, P, E, Ap, Bp, Ae, Be, ap, bp, ae, be, lp, le, var_ap, var_ae, burn, eval, Pfixed, Zfixed, Thetafixed, Afixed, keep_par)
}

