# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GibbsSamplerCpp <- function(M, W, Z, P, E, Ap, Bp, Ae, Be, ap, bp, ae, be, lp, le, var_ap, var_ae, burn, eval, Zfixed, Thetafixed, Afixed, keep_par) {
    .Call('signeR_GibbsSamplerCpp', PACKAGE = 'signeR', M, W, Z, P, E, Ap, Bp, Ae, Be, ap, bp, ae, be, lp, le, var_ap, var_ae, burn, eval, Zfixed, Thetafixed, Afixed, keep_par)
}

